### Data Cleaning and Quality Assessment
### Homework 1 – Tabular Data
### Hadi Seyed

### 1.1 Tidy Data from Excel

In [43]:
import pandas as pd


INPUT_FILE = "Film_Awards.xlsx"


def clean_text(value):
    """Clean whitespace and convert values to strings."""
    if pd.isna(value):
        return None

    value = str(value).strip()

    if value == "":
        return None

    return value


def clean_excel_data(filename):
    # Read the Excel workbook without assuming the first row
    # is necessarily the header.
    raw = pd.read_excel(filename, header=None)

    # Remove completely empty rows and columns.
    raw = raw.dropna(axis=0, how="all")
    raw = raw.dropna(axis=1, how="all")

    # Display the raw structure so that the spreadsheet layout
    # can be inspected.
    print("Raw spreadsheet:")
    print(raw)

    return raw


if __name__ == "__main__":
    df = clean_excel_data(INPUT_FILE)

Raw spreadsheet:
               0                   1  \
0   Best Picture                 NaN
1           Year       Academy Award
2           2019            Parasite
3           2018          Green Book
4           2017  The Shape of Water
7     Best Actor                 NaN
8           Year       Academy Award
9           2019     Joaquin Phoenix
10          2018          Rami Malek
11          2017         Gary Oldman
14  Best Actress                 NaN
15          Year       Academy Award
16          2019     Renée Zellweger
17          2018       Olivia Colman
18          2017   Frances McDormand

                                            2  \
0                                         NaN
1                                    Director
2                                Bong Joon-ho
3                              Peter Farrelly
4                          Guillermo del Toro
7                                         NaN
8                                        Film
9                                       Joker
10                          Bohemian Rhapsody
11                               Darkest Hour
14                                        NaN
15                                       Film
16                                       Judy
17                              The Favourite
18  Three Billboards Outside Ebbing, Missouri

                                            3  \
0                                         NaN
1                        Golden Globe - Drama
2                                        1917
3                           Bohemian Rhapsody
4   Three Billboards Outside Ebbing, Missouri
7                                         NaN
8                        Golden Globe - Drama
9                             Joaquin Phoenix
10                                 Rami Malek
11                                Gary Oldman
14                                        NaN
15                       Golden Globe - Drama
16                            Renée Zellweger
17                                Glenn Close
18                          Frances McDormand

                                            4  \
0                                         NaN
1                                    Director
2                                  Sam Mendes
3                                Bryan Singer
4                             Martin McDonagh
7                                         NaN
8                                        Film
9                                       Joker
10                         Bohemian Rhapsody
11                               Darkest Hour
14                                        NaN
15                                       Film
16                                       Judy
17                                   The Wife
18  Three Billboards Outside Ebbing, Missouri

                                   5                    6
0                                NaN                  NaN
1   Golden Globe - Musical or Comedy             Director
2      Once Upon a Time in Hollywood    Quentin Tarantino
3                         Green Book        Peter Farelly
4                          Lady Bird         Greta Gerwig
7                                NaN                  NaN
8   Golden Globe - Musical or Comedy                 Film
9                      Taron Egerton            Rocketman
10                    Christian Bale                 Vice
11                      James Franco  The Disaster Artist
14                               NaN                  NaN
15  Golden Globe - Musical or Comedy                 Film
16                         Awkwafina         The Farewell
17                    Olivia Coleman      The Favourite\n
18                     Saoirse Ronan            Lady Bird

In [44]:
# Step 1: Load the original data
import pandas as pd

df = pd.read_excel(
    "Film_Awards.xlsx",
    sheet_name="Top Awards",
    header=None
)

print(df)

               0                   1  \
0   Best Picture                 NaN
1           Year       Academy Award
2           2019            Parasite
3           2018          Green Book
4           2017  The Shape of Water
5            NaN                 NaN
6            NaN                 NaN
7     Best Actor                 NaN
8           Year       Academy Award
9           2019     Joaquin Phoenix
10          2018          Rami Malek
11          2017         Gary Oldman
12           NaN                 NaN
13           NaN                 NaN
14  Best Actress                 NaN
15          Year       Academy Award
16          2019     Renée Zellweger
17          2018       Olivia Colman
18          2017   Frances McDormand

                                            2  \
0                                         NaN
1                                    Director
2                                Bong Joon-ho
3                              Peter Farrelly
4                          Guillermo del Toro
5                                         NaN
6                                         NaN
7                                         NaN
8                                        Film
9                                       Joker
10                          Bohemian Rhapsody
11                               Darkest Hour
12                                        NaN
13                                        NaN
14                                        NaN
15                                       Film
16                                       Judy
17                              The Favourite
18  Three Billboards Outside Ebbing, Missouri

                                            3  \
0                                         NaN
1                        Golden Globe - Drama
2                                        1917
3                           Bohemian Rhapsody
4   Three Billboards Outside Ebbing, Missouri
5                                         NaN
6                                         NaN
7                                         NaN
8                        Golden Globe - Drama
9                             Joaquin Phoenix
10                                 Rami Malek
11                                Gary Oldman
12                                        NaN
13                                        NaN
14                                        NaN
15                       Golden Globe - Drama
16                            Renée Zellweger
17                                Glenn Close
18                          Frances McDormand

                                            4  \
0                                         NaN
1                                    Director
2                                  Sam Mendes
3                                Bryan Singer
4                             Martin McDonagh
5                                         NaN
6                                         NaN
7                                         NaN
8                                        Film
9                                       Joker
10                         Bohemian Rhapsody
11                               Darkest Hour
12                                        NaN
13                                        NaN
14                                        NaN
15                                       Film
16                                       Judy
17                                   The Wife
18  Three Billboards Outside Ebbing, Missouri

                                   5                    6
0                                NaN                  NaN
1   Golden Globe - Musical or Comedy             Director
2      Once Upon a Time in Hollywood    Quentin Tarantino
3                         Green Book        Peter Farelly
4                          Lady Bird         Greta Gerwig
5                                NaN                  NaN
6                                NaN                  NaN
7                                NaN                  NaN
8   Golden Globe - Musical or Comedy                 Film
9                      Taron Egerton            Rocketman
10                    Christian Bale                 Vice
11                      James Franco  The Disaster Artist
12                               NaN                  NaN
13                               NaN                  NaN
14                               NaN                  NaN
15  Golden Globe - Musical or Comedy                 Film
16                         Awkwafina         The Farewell
17                    Olivia Coleman      The Favourite\n
18                     Saoirse Ronan            Lady Bird

In [45]:
# dimensions of the original spreadsheet
import pandas as pd

df = pd.read_excel(
    "Film_Awards.xlsx",
    sheet_name="Top Awards",
    header=None
)

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 50)

display(df)

,0,1,2,3,4,5,6
0,Best Picture,NaN,NaN,NaN,NaN,NaN,NaN
1,Year,Academy Award,Director,Golden Globe - Drama,Director,Golden Globe - Musical or Comedy,Director
2,2019,Parasite,Bong Joon-ho,1917,Sam Mendes,Once Upon a Time in Hollywood,Quentin Tarantino
3,2018,Green Book,Peter Farrelly,Bohemian Rhapsody,Bryan Singer,Green Book,Peter Farelly
4,2017,The Shape of Water,Guillermo del Toro,"Three Billboards Outside Ebbing, Missouri",Martin McDonagh,Lady Bird,Greta Gerwig
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Best Actor,NaN,NaN,NaN,NaN,NaN,NaN
8,Year,Academy Award,Film,Golden Globe - Drama,Film,Golden Globe - Musical or Comedy,Film
9,2019,Joaquin Phoenix,Joker,Joaquin Phoenix,Joker,Taron Egerton,Rocketman
10,2018,Rami Malek,Bohemian Rhapsody,Rami Malek,Bohemian Rhapsody,Christian Bale,Vice
11,2017,Gary Oldman,Darkest Hour,Gary Oldman,Darkest Hour,James Franco,The Disaster Artist
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Best Actress,NaN,NaN,NaN,NaN,NaN,NaN
15,Year,Academy Award,Film,Golden Globe - Drama,Film,Golden Globe - Musical or Comedy,Film
16,2019,Renée Zellweger,Judy,Renée Zellweger,Judy,Awkwafina,The Farewell
17,2018,Olivia Colman,The Favourite,Glenn Close,The Wife,Olivia Coleman,The Favourite\n
18,2017,Frances McDormand,"Three Billboards Outside Ebbing, Missouri",Frances McDormand,"Three Billboards Outside Ebbing, Missouri",Saoirse Ronan,Lady Bird

In [46]:
print(df.shape)

(19, 7)

In [47]:
# Step 2: Create the tidy DataFrame
import pandas as pd

tidy_rows = []

# Best Picture
for row in range(2, 5):
    year = df.iloc[row, 0]

    # Academy Award
    tidy_rows.append({
        "Year": year,
        "Award Category": "Best Picture",
        "Organization": "Academy Award",
        "Winner": None,
        "Film": df.iloc[row, 1],
        "Director": df.iloc[row, 2]
    })

    # Golden Globe - Drama
    tidy_rows.append({
        "Year": year,
        "Award Category": "Best Picture",
        "Organization": "Golden Globe - Drama",
        "Winner": None,
        "Film": df.iloc[row, 3],
        "Director": df.iloc[row, 4]
    })

    # Golden Globe - Musical or Comedy
    tidy_rows.append({
        "Year": year,
        "Award Category": "Best Picture",
        "Organization": "Golden Globe - Musical or Comedy",
        "Winner": None,
        "Film": df.iloc[row, 5],
        "Director": df.iloc[row, 6]
    })


# Best Actor
for row in range(9, 12):
    year = df.iloc[row, 0]

    # Academy Award
    tidy_rows.append({
        "Year": year,
        "Award Category": "Best Actor",
        "Organization": "Academy Award",
        "Winner": df.iloc[row, 1],
        "Film": df.iloc[row, 2],
        "Director": None
    })

    # Golden Globe - Drama
    tidy_rows.append({
        "Year": year,
        "Award Category": "Best Actor",
        "Organization": "Golden Globe - Drama",
        "Winner": df.iloc[row, 3],
        "Film": df.iloc[row, 4],
        "Director": None
    })

    # Golden Globe - Musical or Comedy
    tidy_rows.append({
        "Year": year,
        "Award Category": "Best Actor",
        "Organization": "Golden Globe - Musical or Comedy",
        "Winner": df.iloc[row, 5],
        "Film": df.iloc[row, 6],
        "Director": None
    })


# Best Actress
for row in range(16, 19):
    year = df.iloc[row, 0]

    # Academy Award
    tidy_rows.append({
        "Year": year,
        "Award Category": "Best Actress",
        "Organization": "Academy Award",
        "Winner": df.iloc[row, 1],
        "Film": df.iloc[row, 2],
        "Director": None
    })

    # Golden Globe - Drama
    tidy_rows.append({
        "Year": year,
        "Award Category": "Best Actress",
        "Organization": "Golden Globe - Drama",
        "Winner": df.iloc[row, 3],
        "Film": df.iloc[row, 4],
        "Director": None
    })

    # Golden Globe - Musical or Comedy
    tidy_rows.append({
        "Year": year,
        "Award Category": "Best Actress",
        "Organization": "Golden Globe - Musical or Comedy",
        "Winner": df.iloc[row, 5],
        "Film": df.iloc[row, 6],
        "Director": None
    })


# Convert to DataFrame
tidy_df = pd.DataFrame(tidy_rows)

display(tidy_df)

,Year,Award Category,Organization,Winner,Film,Director
0,2019,Best Picture,Academy Award,None,Parasite,Bong Joon-ho
1,2019,Best Picture,Golden Globe - Drama,None,1917,Sam Mendes
2,2019,Best Picture,Golden Globe - Musical or Comedy,None,Once Upon a Time in Hollywood,Quentin Tarantino
3,2018,Best Picture,Academy Award,None,Green Book,Peter Farrelly
4,2018,Best Picture,Golden Globe - Drama,None,Bohemian Rhapsody,Bryan Singer
5,2018,Best Picture,Golden Globe - Musical or Comedy,None,Green Book,Peter Farelly
6,2017,Best Picture,Academy Award,None,The Shape of Water,Guillermo del Toro
7,2017,Best Picture,Golden Globe - Drama,None,"Three Billboards Outside Ebbing, Missouri",Martin McDonagh
8,2017,Best Picture,Golden Globe - Musical or Comedy,None,Lady Bird,Greta Gerwig
9,2019,Best Actor,Academy Award,Joaquin Phoenix,Joker,None
10,2019,Best Actor,Golden Globe - Drama,Joaquin Phoenix,Joker,None
11,2019,Best Actor,Golden Globe - Musical or Comedy,Taron Egerton,Rocketman,None
12,2018,Best Actor,Academy Award,Rami Malek,Bohemian Rhapsody,None
13,2018,Best Actor,Golden Globe - Drama,Rami Malek,Bohemian Rhapsody,None
14,2018,Best Actor,Golden Globe - Musical or Comedy,Christian Bale,Vice,None
15,2017,Best Actor,Academy Award,Gary Oldman,Darkest Hour,None
16,2017,Best Actor,Golden Globe - Drama,Gary Oldman,Darkest Hour,None
17,2017,Best Actor,Golden Globe - Musical or Comedy,James Franco,The Disaster Artist,None
18,2019,Best Actress,Academy Award,Renée Zellweger,Judy,None
19,2019,Best Actress,Golden Globe - Drama,Renée Zellweger,Judy,None
20,2019,Best Actress,Golden Globe - Musical or Comedy,Awkwafina,The Farewell,None
21,2018,Best Actress,Academy Award,Olivia Colman,The Favourite,None
22,2018,Best Actress,Golden Globe - Drama,Glenn Close,The Wife,None
23,2018,Best Actress,Golden Globe - Musical or Comedy,Olivia Coleman,The Favourite\n,None
24,2017,Best Actress,Academy Award,Frances McDormand,"Three Billboards Outside Ebbing, Missouri",None
25,2017,Best Actress,Golden Globe - Drama,Frances McDormand,"Three Billboards Outside Ebbing, Missouri",None
26,2017,Best Actress,Golden Globe - Musical or Comedy,Saoirse Ronan,Lady Bird,None

In [48]:
# Step 3: Clean the data
# Remove unnecessary whitespace
for column in ["Winner", "Film", "Director"]:
    tidy_df[column] = tidy_df[column].apply(
        lambda x: x.strip() if isinstance(x, str) else x
    )

# Correct known spelling errors
tidy_df["Winner"] = tidy_df["Winner"].replace(
    "Olivia Coleman",
    "Olivia Colman"
)

tidy_df["Director"] = tidy_df["Director"].replace(
    "Peter Farelly",
    "Peter Farrelly"
)

# Make sure film titles are strings
tidy_df["Film"] = tidy_df["Film"].apply(
    lambda x: str(x) if pd.notna(x) else x
)

display(tidy_df)

,Year,Award Category,Organization,Winner,Film,Director
0,2019,Best Picture,Academy Award,None,Parasite,Bong Joon-ho
1,2019,Best Picture,Golden Globe - Drama,None,1917,Sam Mendes
2,2019,Best Picture,Golden Globe - Musical or Comedy,None,Once Upon a Time in Hollywood,Quentin Tarantino
3,2018,Best Picture,Academy Award,None,Green Book,Peter Farrelly
4,2018,Best Picture,Golden Globe - Drama,None,Bohemian Rhapsody,Bryan Singer
5,2018,Best Picture,Golden Globe - Musical or Comedy,None,Green Book,Peter Farrelly
6,2017,Best Picture,Academy Award,None,The Shape of Water,Guillermo del Toro
7,2017,Best Picture,Golden Globe - Drama,None,"Three Billboards Outside Ebbing, Missouri",Martin McDonagh
8,2017,Best Picture,Golden Globe - Musical or Comedy,None,Lady Bird,Greta Gerwig
9,2019,Best Actor,Academy Award,Joaquin Phoenix,Joker,None
10,2019,Best Actor,Golden Globe - Drama,Joaquin Phoenix,Joker,None
11,2019,Best Actor,Golden Globe - Musical or Comedy,Taron Egerton,Rocketman,None
12,2018,Best Actor,Academy Award,Rami Malek,Bohemian Rhapsody,None
13,2018,Best Actor,Golden Globe - Drama,Rami Malek,Bohemian Rhapsody,None
14,2018,Best Actor,Golden Globe - Musical or Comedy,Christian Bale,Vice,None
15,2017,Best Actor,Academy Award,Gary Oldman,Darkest Hour,None
16,2017,Best Actor,Golden Globe - Drama,Gary Oldman,Darkest Hour,None
17,2017,Best Actor,Golden Globe - Musical or Comedy,James Franco,The Disaster Artist,None
18,2019,Best Actress,Academy Award,Renée Zellweger,Judy,None
19,2019,Best Actress,Golden Globe - Drama,Renée Zellweger,Judy,None
20,2019,Best Actress,Golden Globe - Musical or Comedy,Awkwafina,The Farewell,None
21,2018,Best Actress,Academy Award,Olivia Colman,The Favourite,None
22,2018,Best Actress,Golden Globe - Drama,Glenn Close,The Wife,None
23,2018,Best Actress,Golden Globe - Musical or Comedy,Olivia Colman,The Favourite,None
24,2017,Best Actress,Academy Award,Frances McDormand,"Three Billboards Outside Ebbing, Missouri",None
25,2017,Best Actress,Golden Globe - Drama,Frances McDormand,"Three Billboards Outside Ebbing, Missouri",None
26,2017,Best Actress,Golden Globe - Musical or Comedy,Saoirse Ronan,Lady Bird,None

In [49]:
print(tidy_df["Winner"].unique())

[None 'Joaquin Phoenix' 'Taron Egerton' 'Rami Malek' 'Christian Bale'
 'Gary Oldman' 'James Franco' 'Renée Zellweger' 'Awkwafina'
 'Olivia Colman' 'Glenn Close' 'Frances McDormand' 'Saoirse Ronan']

In [50]:
print(tidy_df["Director"].unique())

['Bong Joon-ho' 'Sam Mendes' 'Quentin Tarantino' 'Peter Farrelly'
 'Bryan Singer' 'Guillermo del Toro' 'Martin McDonagh' 'Greta Gerwig' None]

In [51]:
for column in ["Winner", "Film", "Director"]:
    print(
        column,
        tidy_df[column]
        .dropna()
        .apply(lambda x: x != x.strip())
        .sum()
    )

Winner 0
Film 0
Director 0

In [54]:
# Sort the tidy data
tidy_df = tidy_df.sort_values(
    [
        "Year",
        "Award Category",
        "Organization"
    ]
).reset_index(drop=True)



# Sort the tidy data from 2019 to 2017
tidy_df = tidy_df.sort_values(
    "Year",
    ascending=False
).reset_index(drop=True)

# # Sort the tidy data from 2017 to 2019
# tidy_df = tidy_df.sort_values(
#     "Year",
#     ascending=True
# ).reset_index(drop=True)



# Display the tidy DataFrame
print("\nTIDY DATA")
print("=" * 80)

print(tidy_df.to_string(index=False))


# Save the tidy data to a new Excel file
output_file = "Film_Awards_Tidy2.xlsx"

tidy_df.to_excel(
    output_file,
    index=False,
    sheet_name="Tidy Data"
)

print("\n" + "=" * 80)
print(f"Tidy data saved to: {output_file}")
print(f"Number of rows: {len(tidy_df)}")
print(f"Number of columns: {len(tidy_df.columns)}")

TIDY DATA
================================================================================
 Year Award Category                     Organization            Winner                                      Film           Director
 2019   Best Picture Golden Globe - Musical or Comedy              None             Once Upon a Time in Hollywood  Quentin Tarantino
 2019   Best Picture             Golden Globe - Drama              None                                      1917         Sam Mendes
 2019   Best Picture                    Academy Award              None                                  Parasite       Bong Joon-ho
 2019   Best Actress Golden Globe - Musical or Comedy         Awkwafina                              The Farewell               None
 2019   Best Actress             Golden Globe - Drama   Renée Zellweger                                      Judy               None
 2019   Best Actress                    Academy Award   Renée Zellweger                                      Judy               None
 2019     Best Actor Golden Globe - Musical or Comedy     Taron Egerton                                 Rocketman               None
 2019     Best Actor             Golden Globe - Drama   Joaquin Phoenix                                     Joker               None
 2019     Best Actor                    Academy Award   Joaquin Phoenix                                     Joker               None
 2018   Best Actress Golden Globe - Musical or Comedy     Olivia Colman                             The Favourite               None
 2018   Best Picture Golden Globe - Musical or Comedy              None                                Green Book     Peter Farrelly
 2018   Best Picture             Golden Globe - Drama              None                         Bohemian Rhapsody       Bryan Singer
 2018   Best Picture                    Academy Award              None                                Green Book     Peter Farrelly
 2018   Best Actress             Golden Globe - Drama       Glenn Close                                  The Wife               None
 2018   Best Actress                    Academy Award     Olivia Colman                             The Favourite               None
 2018     Best Actor Golden Globe - Musical or Comedy    Christian Bale                                      Vice               None
 2018     Best Actor             Golden Globe - Drama        Rami Malek                         Bohemian Rhapsody               None
 2018     Best Actor                    Academy Award        Rami Malek                         Bohemian Rhapsody               None
 2017     Best Actor             Golden Globe - Drama       Gary Oldman                              Darkest Hour               None
 2017   Best Picture Golden Globe - Musical or Comedy              None                                 Lady Bird       Greta Gerwig
 2017   Best Picture             Golden Globe - Drama              None Three Billboards Outside Ebbing, Missouri    Martin McDonagh
 2017   Best Picture                    Academy Award              None                        The Shape of Water Guillermo del Toro
 2017   Best Actress Golden Globe - Musical or Comedy     Saoirse Ronan                                 Lady Bird               None
 2017   Best Actress             Golden Globe - Drama Frances McDormand Three Billboards Outside Ebbing, Missouri               None
 2017   Best Actress                    Academy Award Frances McDormand Three Billboards Outside Ebbing, Missouri               None
 2017     Best Actor Golden Globe - Musical or Comedy      James Franco                       The Disaster Artist               None
 2017     Best Actor                    Academy Award       Gary Oldman                              Darkest Hour               None

================================================================================
Tidy data saved to: Film_Awards_Tidy2.xlsx
Number of rows: 27
Number of columns: 6

### Question 1: For each film involved in multiple awards, list the award and year it is associated with.

In [52]:
film_counts = (
    tidy_df
    .dropna(subset=["Film"])
    .groupby("Film")
    .size()
)

multiple_films = film_counts[film_counts > 1]

film_results = tidy_df[
    tidy_df["Film"].isin(multiple_films.index)
].sort_values(
    ["Film", "Year"]
)

display(
    film_results[
        ["Film", "Year", "Award Category", "Organization"]
    ]
)

,Film,Year,Award Category,Organization
4,Bohemian Rhapsody,2018,Best Picture,Golden Globe - Drama
12,Bohemian Rhapsody,2018,Best Actor,Academy Award
13,Bohemian Rhapsody,2018,Best Actor,Golden Globe - Drama
15,Darkest Hour,2017,Best Actor,Academy Award
16,Darkest Hour,2017,Best Actor,Golden Globe - Drama
3,Green Book,2018,Best Picture,Academy Award
5,Green Book,2018,Best Picture,Golden Globe - Musical or Comedy
9,Joker,2019,Best Actor,Academy Award
10,Joker,2019,Best Actor,Golden Globe - Drama
18,Judy,2019,Best Actress,Academy Award
19,Judy,2019,Best Actress,Golden Globe - Drama
8,Lady Bird,2017,Best Picture,Golden Globe - Musical or Comedy
26,Lady Bird,2017,Best Actress,Golden Globe - Musical or Comedy
21,The Favourite,2018,Best Actress,Academy Award
23,The Favourite,2018,Best Actress,Golden Globe - Musical or Comedy
7,"Three Billboards Outside Ebbing, Missouri",2017,Best Picture,Golden Globe - Drama
24,"Three Billboards Outside Ebbing, Missouri",2017,Best Actress,Academy Award
25,"Three Billboards Outside Ebbing, Missouri",2017,Best Actress,Golden Globe - Drama

### Question 2: For each actor/actress winning multiple awards, list the film and award they are associated with.

In [53]:
winner_counts = (
    tidy_df
    .dropna(subset=["Winner"])
    .groupby("Winner")
    .size()
)

multiple_winners = winner_counts[
    winner_counts > 1
]

actor_results = tidy_df[
    tidy_df["Winner"].isin(multiple_winners.index)
].sort_values(
    ["Winner", "Year"]
)

display(
    actor_results[
        [
            "Winner",
            "Film",
            "Year",
            "Award Category",
            "Organization"
        ]
    ]
)

,Winner,Film,Year,Award Category,Organization
24,Frances McDormand,"Three Billboards Outside Ebbing, Missouri",2017,Best Actress,Academy Award
25,Frances McDormand,"Three Billboards Outside Ebbing, Missouri",2017,Best Actress,Golden Globe - Drama
15,Gary Oldman,Darkest Hour,2017,Best Actor,Academy Award
16,Gary Oldman,Darkest Hour,2017,Best Actor,Golden Globe - Drama
9,Joaquin Phoenix,Joker,2019,Best Actor,Academy Award
10,Joaquin Phoenix,Joker,2019,Best Actor,Golden Globe - Drama
21,Olivia Colman,The Favourite,2018,Best Actress,Academy Award
23,Olivia Colman,The Favourite,2018,Best Actress,Golden Globe - Musical or Comedy
12,Rami Malek,Bohemian Rhapsody,2018,Best Actor,Academy Award
13,Rami Malek,Bohemian Rhapsody,2018,Best Actor,Golden Globe - Drama
18,Renée Zellweger,Judy,2019,Best Actress,Academy Award
19,Renée Zellweger,Judy,2019,Best Actress,Golden Globe - Drama